SMAT-140: cut client port
soverenio/traefik pull request #11
Opened 2021-09-22 14:57 UTC by pavlushev

cut client port

2021-09-22 15:27 UTC, bigbes commented on pkg/middlewares/replicate/replicate.go
> +	remoteAddr, _, err := net.SplitHostPort(req.RemoteAddr)
> SplitHostPort splits a network address of the form "host:port", "host%zone:port", "[host]:port" or "[host%zone]:port" into host or host%zone and port.

Может быть стоит сделать какую-то закладку на случай пустого host

2021-09-22 15:37 UTC, uhzxl approved these changes

2021-09-23 07:13 UTC, pavlushev commented on pkg/middlewares/replicate/replicate.go
> +	remoteAddr, _, err := net.SplitHostPort(req.RemoteAddr)
добавлял в спеку проверку

2021-09-23 08:49 UTC, megge-dream commented on pkg/middlewares/replicate/replicate.go
> +	remoteAddr, _, err := net.SplitHostPort(req.RemoteAddr)
получается запросы с пустым host никогда не уйдут из кафки? stats же при их отправке вернет digger'у ошибку, и будут они там вечно крутиться. может все-таки здесь с этим что-то сделаем?

2021-09-23 09:38 UTC, pavlushev commented on pkg/middlewares/replicate/replicate.go
> +	remoteAddr, _, err := net.SplitHostPort(req.RemoteAddr)
если логическая ошибка там диггер должен откинуть сообщение
он вернет в очередь только если проблемы с доставкой

2021-09-23 09:58 UTC, megge-dream requested changes

2021-09-23 09:58 UTC, megge-dream commented on pkg/middlewares/replicate/replicate.go
> +	"fmt"
fmt не используется в файле (из-за этого тесты на pr упали)

2021-09-23 10:01 UTC, pavlushev commented on pkg/middlewares/replicate/replicate.go
> +	"fmt"
fixed

2021-09-23 10:09 UTC, megge-dream approved these changes

2021-09-23 10:34 UTC, bigbes approved these changes

2021-09-23 10:48 UTC, merged